inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
  marching_cubes_bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
data:
  input_folder: Datasets/Replica/office3
  output: output/Replica/office3