inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
  marching_cubes_bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
data:
  input_folder: Datasets/Replica/office2
  output: output/Replica/office2