dataset: 'scannet'
sync_method: strict
coarse: True
verbose: False
meshing:
  resolution: 512
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 20
  ignore_edge_H: 20
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.0005      
  pixels: 1000
  iters: 30
mapping:
  every_frame: 5
  vis_freq: 500
  vis_inside_freq: 30
  mesh_freq: 500
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 10
  pixels: 1000
  iters_first: 400
  iters: 400
  bound: [[0.0,6.5],[0.0,4.0],[0,3.5]]
  marching_cubes_bound: [[0.0,6.5],[0.0,4.0],[0,3.5]]
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10
data:
  input_folder: Datasets/Demo
  output: output/Demo